<template>
  <div>
    <h1>Principles</h1>
    <div class="aux">
      <a href="https://docs.google.com/document/d/1GWAdhbJy4Y89TYvRL2eycuprJaDbW-yX8EuzjnObt2M/edit">Google Doc</a>
      <p>Principles to guide responsible data handling toward saving children’s lives, defending their rights, and helping them fulfill their potential from early childhood through adolescence.</p>
      <p>[Download the Report]</p>
      <p>RD4C seeks to build awareness regarding the need for special attention to data issues affecting children—especially in this age of changing technology and data linkage; and to engage with governments, communities, and development actors to put the best interests of children and a child rights approach at the center of our data activities. The right data in the right hands at the right time can significantly improve outcomes for children. The challenge is to understand the potential risks and ensure that the collection, analysis and use of data on children does not undermine these benefits.</p>
      <p>Drawing upon field-based research and established good practice, RD4C aims to highlight and support best practice in our work; identify challenges and develop practical tools to assist practitioners in evaluating and addressing them; and encourage a broader discussion on actionable principles, insights, and approaches for responsible data management.</p>
      <h2>Principles</h2>
      <p>(Download a one-page summary of all principles together here)</p>
    </div>
    <ul>
      <li v-for="i in principles_temp">
        <rd-principle-card :content="i"/> 
      </li>
    </ul>
  </div>
</template>

<script setup>
// Vamos pegar os dados da lista de principles (Directus)

const principles_temp = [
  {
    "name": "Participatory",
    "short_description": "Engaging and informing individuals and groups affected by the use of data for and about children.",
    "long_description": "Responsible data is participatory. It seeks and builds with inputs from those who use and are affected by data, namely children, their caregivers, and the communities in which they live. Accordingly, actors should inform and engage with individuals and groups. In seeking input, actors should pay attention to marginalized and vulnerable population segments as well as to the inputs of partners, donors and other key stakeholders.",
    "color": "yellow",
    "id": "rec1AHb9vu12DJIMc"
  },
  {
    "name": "Professionally Accountable",
    "short_description": "Operationalizing responsible data practices and principles by establishing institutional processes, roles, and responsibilities.",
    "long_description": "Data responsibility rests upon broader foundations of professional accountability. To ensure that the practices and principles described above are put in action, and the unique considerations of responsible data for children are operationalized within institutional processes, organizations and partners should collect, process, and use data within a more general culture of data responsibility. Such a culture has many elements, but one of the most important is to establish and clearly define the role of organization-wide data stewards. Data stewards are an emerging role; they are individuals or groups whose duties cut across departments and functions, and whose broad remit is to oversee responsibility and accountability in the way data is handled.",
    "color": "green",
    "id": "rec1kPxJfR6zNJHlA"
  },
  {
    "name": "People-Centric",
    "short_description": "Ensuring the needs and expectations of children, their caregivers, and their communities are prioritized by actors handling data for and about them.",
    "long_description": "Much of the data used for drawing insights to improve children’s lives involves or is generated by people. The insights from it have the potential to impact the lives of children in many ways, both positive and negative. Actors must thus ensure the needs, interests and expectations of people—including children and their caregivers in particular—are prioritized by those handling data about them. Actors should take a people-centric approach to the consideration of opportunities and risks of data initiatives—prioritizing the consideration of data practices’ effects on people over potential efficiency gains or other process-oriented objectives. This entails some combination of the following criteria: children and/or their caregivers have consented to the data use, children and/or their caregivers have a clear understanding of how this work will be conducted, the work is demonstrably serving children’s interests, and/or the work is required by law or institutional mandate. In addition, actors need to be context sensitive, paying attention to and acting according to the legal, cultural and community contexts in which any given project exists.",
    "color": "orange",
    "id": "recUZnnRLQ0gYnaJb"
  },
  {
    "name": "Prevention of Harms across the Data Life Cycle",
    "short_description": "Establishing end-to-end data responsibility by assessing risks during the collecting, storing, preparing, sharing, analyzing, and using stages of the data life cycle.",
    "long_description": "Data is not static but exists on a cycle. As part of a commitment to data responsibility, actors should assess and seek to prevent risks across the full data life cycle, including the collecting, storing and preparing, sharing, analyzing and using stages. This concept is called end-to-end data responsibility. It is essential for preventing harm to children and ensuring trust.",
    "color": "purple",
    "id": "recW8aVQIcNIQmIao"
  },
  {
    "name": "Proportional",
    "short_description": "Aligning the breadth of data collection and duration of data retention with the intended purpose.",
    "long_description": "In the data space, less can sometimes be more. When developing and implementing data initiatives, actors should always consider necessity and whether there is proportionality in the breadth of data collection and duration of data retention in order to achieve the intended purpose. The collection and retention of data should be relevant, limited and adequate to what is necessary for achieving intended purposes. The importance of targeting and minimizing collection is true of all data, but especially true of data related to children, given potential and actual vulnerabilities.",
    "color": "red",
    "id": "recfANbdqMllKdw6d"
  },
  {
    "name": "Protective of Children’s Rights",
    "short_description": "Recognizing the distinct rights and requirements for helping children develop to their full potential.",
    "long_description": "When it comes to children, responsible data practices begin by recognizing their distinct needs and requirements. Children’s rights must be realized in order for them to develop to their full potential. Realizing these rights can be complex given children’s inherent vulnerabilities, the likelihood that others are making impactful decisions on their behalf, and the future prospects they can achieve if supported effectively by those working in their interest.",
    "color": "blue",
    "id": "reckNntC13XWtDnjN"
  },
  {
    "name": "Purpose-Driven",
    "short_description": "Identifying and specifying why the data is needed and how the intended or potential benefits relate to improving children’s lives.",
    "long_description": "A responsible data practice starts by being purpose-driven. When seeking to handle data actors should identify and specify why the data is needed and how the intended or potential benefits relate to improving children’s lives. If there is no clearly articulated benefit for children, actors should not collect data, store, share or analyze it.",
    "color": "purple",
    "id": "recyfyYX7PPnEgsrU"
  }
]



</script>

<style scoped lang="scss">

</style>
